version: "3.5"

services:
  pizza:
    build: .
    networks:
      - proxy
      - default
    container_name: pizza
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pizza.entrypoints=web"
      - "traefik.http.routers.pizza.rule=Host(`pizza.${PWDOCKER_DOMAIN}`)"
      - "traefik.http.routers.pizza.service=pizza-pizza-configurator"

networks:
  proxy:
    external: true
